### Login
# @name Login
POST {{api}}/auth/login
Content-Type: application/json

{
    "username": "superadminusername",
    "password": "loremipsum"
}

### Get token
@token = {{Login.response.body.data.token}}


### Create user
POST {{api}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "usernames",
    "email": "newusers@email.com",
    "password": "loremipsum",
    "password_conf": "loremipsum",
    "role_ids": [
        "00000000-0000-0000-0000-000000000001"
    ]
}

### Get all users
GET {{api}}/users?page=1&limit=10
Authorization: Bearer {{token}}